name: teeproxy

on:
  create:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build Image
        run: docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6 -t inerplat/teeproxy:latest --push .
